# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21b22bdfb965763ca8d075a07d327ba7a22c2b4edcf84d7eb088ac50e057dc925c7fcf0a856f536458980fd42702666e6b95b373262a78c0e9903d5016d2687

test:
  secret_key_base: d35e4f62ac0ac67ce04c702b26b88a6d87385d55350a0cdd625ae0a4fde5c32f8adf8838d752096fa3c04600ad981842d16499be8a3e5210f8092e9a0c295704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
